### ISSUE TITLE
Multiple environments at once - as array.

### ISSUE THREAD

**Issue by IngwiePhoenix** [mdreizin/webpack-config#11]
Hey.

So, my WebPack config has crossed the 400th LoC. Holy ... y'know. ITS BIG.

The idea is, to split it into pieces. In order to do so, I looked at this module. Now I have a few questions:

- Can I have two environments at once?
WebPack's compiler API allows for an array to be supplied, which just spawns two compilers. That would be useful for taking notes of the differences between `dev` and `production` without having to stop the server.

- Is there a clear documentation of the functions? I kinda have to puzzle it together from the README.

Kind regards,
Ingwie

**Comment by mdreizin** [comment]
@IngwiePhoenix Sorry for delayed response.

> Can I have two environments at once?

Just you need to create some configs:

`webpack.dev.config.js`
```js
module.exports = {};
```

`webpack.production.config.js`
```js
module.exports = {};
```

`webpack.config.js`
```js
var WebpackConfig = require('webpack-config');

module.exports = new WebpackConfig().extend('./webpack.[env].config.js');
```

and then you can pass `webpack.config.js` to `webpack` compiler.

You can set `[env]` via:
- `process.env.*`:

```js
env=dev webpack webpack.config.js
```

- API:

```js
var WebpackConfig = require('webpack-config');

WebpackConfig.environment.setAll({
    env: function() {
        return process.env.WEBPACK_ENV || process.env.NODE_ENV;
    }
});
```

> Is there a clear documentation of the functions? I kinda have to puzzle it together from the README.

Yes, it's puzzle. It was automatically generated by `jsdoc`:

https://github.com/mdreizin/webpack-config/blob/master/docs/API.md#Config
https://github.com/mdreizin/webpack-config/blob/master/docs/API.md#Config.environment

**Comment by mdreizin** [comment]
@IngwiePhoenix Please see https://github.com/mdreizin/webpack-config#samples
