### ISSUE TITLE
List breaking changes in v5

### ISSUE THREAD

**Issue by SimenB** [mdreizin/webpack-config#13]
Manually comparing old vs new API is a no-go, it's too large for that.

Keeping a `CHANGELOG` would be nice as well 😄

**Comment by mdreizin** [comment]
@SimenB I will add it.

**Comment by mdreizin** [comment]
@SimenB Please look at https://github.com/mdreizin/webpack-config/wiki/Changelog

**Comment by SimenB** [comment]
Sweet, thanks!
