### ISSUE TITLE
Config environment variable not replaced by merge

### ISSUE THREAD

**Issue by cdreve** [mdreizin/webpack-config#26]
Hi,

I would like to do be able to build multiple variations of the same app.
Very basic example:

`webpack.config.js`

```javascript
ConfigEnvironment.INSTANCE.setAll({
    env: () => process.env.WEBPACK_ENV || process.env.NODE_ENV
    theme: () => argv.THEME || 'default'
});

export default new Config().extend('./webpack.base.config.js');

```
`webpack.base.config.js`

```javascript
export default new Config().merge({
    entry: 'path/[theme]/App.js'
    ...
});
```

`[theme]` is not replaced when used with merge.
`.extend('./webpack.[theme].config.js')` would work.

Is there a reason why `[theme]` is not replaced by merge?

Thank you

**Comment by mdreizin** [comment]
@cdreve It is not supported now, `webpack-config` replaces only params of `.extend('path/[theme]/App.js')` method.

I have some plans to do that and I will add `merge`/`default` strategies which would support that behaviour.

**Comment by cdreve** [comment]
@mdreizin Cool, thank you. Until then I am making the replace manually. It will look a lot better after we have this behaviour :)

**Comment by mdreizin** [comment]
@cdreve I have just added that feature, now all `String` values are preprocessed by [`ConfigOptionsResolver.js`](https://github.com/mdreizin/webpack-config/blob/master/src/ConfigOptionsResolver.js).

Please update to the latest version (`6.1.0`) and close that issues if everything is ok.

**Comment by mdreizin** [comment]
@cdreve Also if you interested how it was implemented please see [`ConfigMergeCommand.js `](https://github.com/mdreizin/webpack-config/blob/master/src/ConfigMergeCommand.js)

**Comment by mdreizin** [comment]
@cdreve I have forgot to tell you about some breaking changes in new release. Please see more at [changelog](https://github.com/mdreizin/webpack-config/wiki/Changelog#v600).

**Comment by mdreizin** [comment]
@cdreve Please update to `6.1.2`.

**Comment by Dictory** [comment]
hello, any updates?
