### ISSUE TITLE
Externals must be arrays in order to merge

### ISSUE THREAD

**Issue by blink1073** [mdreizin/webpack-config#27]
The following works if both are arrays:

```javascript
var Config = require('webpack-config').Config;

var config = new Config();
config.merge({
    externals: {
        'foo': 'bar'
    }
});

config.merge({
    externals: [
        {
          'fizz': 'buzz'
        }
    ]
});

console.log(config);  \\ "Config { externals: [ { fizz: 'buzz' } ] }"
```

**Comment by blink1073** [comment]
The examples in the webpack docs use both forms:
https://webpack.github.io/docs/library-and-externals.html#examples
https://webpack.github.io/docs/configuration.html#externals

**Comment by mdreizin** [comment]
@blink1073 Thanks for feedback. I am going to fix that soon.

**Comment by blink1073** [comment]
Great, and thanks for this library!

**Comment by mdreizin** [comment]
@blink1073 I have refactored code to integrate new features and also fix existing issues easily. Now [`#merge()`](https://github.com/mdreizin/webpack-config/blob/master/src/Config.js#L178) uses [`ConfigMergeCommand.js`](https://github.com/mdreizin/webpack-config/blob/master/src/ConfigMergeCommand.js).

Next I will fix `ConfigMergeCommand` to support appropriate behaviour.

**Comment by mdreizin** [comment]
@blink1073 As I understand the result will be?

```json
{
	"externals": [{
		"foo": "bar"
	}, {
		"fizz": "buzz"
	}]
}
```

**Comment by blink1073** [comment]
@mdreizin, yep, that's what I'd expect.

**Comment by mdreizin** [comment]
@blink1073 Please update to `6.1.1`.

**NOTE**: Before that please read [changelog](https://github.com/mdreizin/webpack-config/wiki/Changelog).

**Comment by mdreizin** [comment]
@blink1073 If everything is ok please feel free to close this issue.

**Comment by blink1073** [comment]
Confirmed: `Config { externals: [ { foo: 'bar' }, { fizz: 'buzz' } ] }`, thanks!

**Comment by mdreizin** [comment]
@blink1073 welcome ;)

**Comment by mdreizin** [comment]
@blink1073 Please update to `6.1.2`, because some issues have been reported and they have just been fixed.

**Comment by blink1073** [comment]
Noted, thanks.
