### ISSUE TITLE
TypeError: Config is not a constructor

### ISSUE THREAD

**Issue by zbuttram** [mdreizin/webpack-config#29]
Hi there, I'd love to be using this awesome library for managing my webpack configs, but I'm having some issues getting it working. I'm using Node 6.3.1 and importing the library with `var Config = require('webpack-config);` but I'm getting the error in the screenshot below. I also get the same TypeError when trying to import with `var Config = require('webpack-config').Config` instead. I believe I'm doing something wrong, but I can't tell what. I know the documentation is using `import` statements, but Node doesn't seem to support these even in the latest stable release.

![image](https://cloud.githubusercontent.com/assets/396699/17264039/5a27c0f0-5599-11e6-9400-fc65a196b229.png)

**Comment by K-Eo** [comment]
Hi!, seems you are missing this:
 
`var Config = require('webpack-config').Config;

module.exports = new Config().extend('webpack.base.config.js').merge({`

Hope this can help you.

**Comment by mdreizin** [comment]
@zbuttram Could you please provide more detailed example?

**Comment by zbuttram** [comment]
@mdreizin Of course. Sorry, I thought the error might have been enough, honestly thought I was just missing something obvious. Here's the full versions of the files I'm trying to use: https://gist.github.com/zbuttram/f658b4747927353fe9203fb09e354d45

**Comment by zbuttram** [comment]
@mdreizin solved this for me in a comment on the gist I linked. Solution is to use `var Config = require('webpack-config').default;` when importing with ES5. Thanks again for the great tool @mdreizin!
