### ISSUE TITLE
In need of a bit more documentation

### ISSUE THREAD

**Issue by Anahkiasen** [mdreizin/webpack-config#4]
This package is a great help, but the documentation isn't helping me much harnessing it at its full power. Could we have more informations on the difference between merge and extends? What does `default` do? What are MultiConfigs?

**Comment by mdreizin** [comment]
@Anahkiasen [`defaults`] (https://lodash.com/docs#defaults) does merging without overriding existing props, `merge` does [`extend`](https://lodash.com/docs#assign). `MultiConfig` will be removed in the next version and it will be replaced just with `Config[]` array. Currently it is array-like object.

**Comment by Anahkiasen** [comment]
Ok! Do you have an example of what you mean by "without overriding existing props"? In which case would `merge` override things? Seems to append whenever possible from what I've seen

**Comment by mdreizin** [comment]
@Anahkiasen I'm currently working on #7 and I will add more docs.

**Comment by mdreizin** [comment]
@Anahkiasen what kind of documentation do you need? New API is done and I'd like to move forward, but need your feedback.

**Comment by Anahkiasen** [comment]
Sorry, all good on this one!
