### ISSUE TITLE
Deep loader query objects are reserialized incorrectly

### ISSUE THREAD

**Issue by exogen** [mdreizin/webpack-config#45]
Hi @mdreizin!

We're having [an issue](https://github.com/walmartlabs/stylus-relative-loader/pull/16) over at `stylus-relative-loader` that I think I tracked down to `webpack-config`. We're on the latest, 6.1.2.

To summarize, this loader string goes in:

```
stylus-relative-loader?{"precacheImportVariables":[{"$tenant":"sams"},{"$tenant":"walmart"}]}
```

and after a `WebpackConfig().merge(...)`, this comes out:

```
stylus-relative-loader?{"precacheImportVariables":[object Object]}
```

^ notice how it clobbered our array! 😱 The original nested object was a totally legit query.

I haven't dug into the `webpack-config` code yet, but I think it might be a bigger issue than just reserializing our object poorly: webpack says that queries can be any old arbitrary syntax and it's the loader's job to parse them – many just happen to use `parseQuery` from `loader-utils` which lets you put JSON5 there, but it's not a requirement. I think it's too presumptuous of `webpack-config` to think it can parse a stringified query. If the loader is already non-stringified (specified like `{ loader: "foo", query: { ... } }`), then sure, but otherwise there's potential breakage.

I'll start digging into the code but would of course appreciate any help. :)

/cc @jmcriffey

**Comment by mdreizin** [comment]
@exogen Hello @exogen, I will take a look at this issue and try to fix it as soon as possible.

**Comment by exogen** [comment]
Nice timing @mdreizin! I just managed to put together a test case: #46.

**Comment by mdreizin** [comment]
Hello again @exogen @jmcriffey,

I have just fixed this issue and I would ask you to update to `6.1.3` version.

Could you please tell me does it work or not?

**Comment by jmcriffey** [comment]
Preliminary testing shows the fix does indeed address our issue. I'm going to do a bit more testing to verify, but I think this does it. Thanks @mdreizin!

**Comment by exogen** [comment]
Confirmed that this is working in our full project now and I can close our workaround. Thank you @mdreizin!!
