### ISSUE TITLE
Prepend entry point

### ISSUE THREAD

**Issue by Anahkiasen** [mdreizin/webpack-config#5]
I have two configuration: local and HMR. In HMR I'd like to override the entry point to prepend the webpack-dev-server related things:

```js
var config = Config.fromObject({
    entry: ['file.js'],
});

if (hmr) {
    config = config.merge({
        entry: [
            'webpack-dev-server/client',
            'webpack/hot/only-dev-server',
        ],
    });
}
```

However of course when I do this, the HMR related entry points are added _after_ my actual entry point. Is there any way to prepend instead of append?

Currently manually overriding `config.entry` afterwards but that's not ideal:

```js
config.entry = [
    'webpack-dev-server/client',
    'webpack/hot/only-dev-server',
].concat(config.entry);
```

**Comment by mdreizin** [comment]
Hello @Anahkiasen,

Thanks for the feedback. I'm currently working on more powerful version of `webpack-config`.

You can include multiple config at once.

Example:

```js
'use strict';

var WebpackConfig = require('webpack-config');

module.exports = new WebpackConfig().extend({
    '../webpack.base.config.js': function(config) {
        // Modify `../webpack.base.config.js`, `config` will be instance of `Config`
        return config;
    }
}).merge({
    filename: __filename,
    entry: {
        vendor: [
            'consolelog',
            'es5-shim',
            'es5-shim/es5-sham',
            'es6-shim',
            'es6-shim/es6-sham',
            'json3',
            'html5shiv',
            'html5shiv/dist/html5shiv-printshiv.js',
            'respond'
        ]
    }
});
```

**Comment by mdreizin** [comment]
@Anahkiasen Please see #7.

**Comment by mdreizin** [comment]
@Anahkiasen I will find better way how to do it. Now it is possible, because now API is independent. Just we need it is refactor of [./lib/configMergeMixin.js](https://github.com/mdreizin/webpack-config/blob/master/lib/configMergeMixin.js).
