### ISSUE TITLE
Doesn't work with webpack 2

### ISSUE THREAD

**Issue by sqal** [mdreizin/webpack-config#53]
```
 WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'DEPENDENCY_TREE'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           DEPENDENCY_TREE: ...
         }
       })
     }
```

Looks like Webpack 2 doesnt like any additional properties inside configuration object that shouldn't be there. Is there any workaround for this? Can i somehow remove this `DEPENDENCY_TREE` object?

**Comment by mdreizin** [comment]
Hello, I'm on vocation now and I will take a look how to solve this issue
next week.

**Comment by mdreizin** [comment]
@sqal Could you please share your config if it is possible?

**Comment by sqal** [comment]
@mdreizin Hi. Yes, clone this repo https://github.com/sqal/webpack-config-test

You can see that when you run `npm run dev` webpack compiles config correctly. But when your run `npm run dev:webpack-config` then it throws this error i mentioned earlier.

**Comment by mdreizin** [comment]
@sqal Thanks. I have just cloned the repo and I would suggest to use temporary workaround (add `.toObject()`):

```js
module.exports = new Config().extend('config/webpack.config.base.js').merge({}).toObject();
```

Why does it needed?

When you call `extend` method it builds dependency tree (`this['DEPENDENCY_TREE']`) internally.

`webpack` team has added [validation of config object](https://github.com/webpack/webpack/blob/master/lib/validateWebpackOptions.js) and it doesn't know about `DEPENDENCY_TREE` property.

I have tried to use `WeakMap` to hold `DEPENDENCY_TREE`, but `babel` uses its own implementation of `WeakMap` and it loses reference of `config` variables.

I will try to find proper way to make it compatible with `webpack 2` without calling `toObject()`.

**Comment by sqal** [comment]
@mdreizin  Awesome :kissing_heart: Thanks for explanation.

**Comment by mdreizin** [comment]
@sqal I have found the solution.

Could you please check out the [develop](https://github.com/mdreizin/webpack-config/tree/develop) branch and test it?

**Comment by mdreizin** [comment]
@sqal In this case you don't need to call `toObject`.

**Comment by mdreizin** [comment]
@sqal I have just tested it and it looks like that everything works fine. Please wait for #55.

**Comment by mdreizin** [comment]
@sqal Please update to `6.2.0`.

**Comment by sqal** [comment]
@mdreizin Good work 👍  Thank you very much.
