### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by mdreizin** [mdreizin/webpack-config#8]
When you have the following error:

```
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "i" "webpack-config"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/webpack-config
npm ERR! 404 
npm ERR! 404 'webpack-config' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-webpack-build'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I'm working on that.

Please use as temporary solution:

```json
{
  "webpack-config": "mdreizin/webpack-config#v0.8.0"
}
```

or

```json
{
  "webpack-config": "0.8.1"
}
```

Please accept my apologies for any inconvenience.

**Comment by basketofsoftkittens** [comment]
+1

**Comment by pheuter** [comment]
yeah, this is a problem now with node modules out of our control that depend on `webpack-config` as well, like **gulp-webpack-build**.

is there an eta on the fix? any ideas what may be causing this? thanks!

**Comment by mdreizin** [comment]
I'm sorry for inconvenience. I have sent email about that to npm support and I'm waiting for response. For now you can install latest version. It is `0.8.1`.

**Comment by mdreizin** [comment]
You can use new version `1.0.2`. It easy to migrate, just you need:

- `extend()` should be renamed to `merge()`;
- `fromFile()`, `fromDirectory()`, `fromCwd()` should be renamed to `extend()`. Now it supports loading of configs directly: `extend('./webpack.config.js')` or `extend('shared-config')` where `shared-config` is node module.

**Comment by tmpvar** [comment]
@mdreizin are you unpublishing all of the old versions manually or is there some tool doing this for you?

**Comment by mdreizin** [comment]
@tmpvar Unfortunately yes, I did `npm unpublish .` manually instead of `npm unpublish`. Now I have switched to [semantic-release](https://github.com/semantic-release/semantic-release).

**Comment by tmpvar** [comment]
@mdreizin ah, woops!

**Comment by timoxley** [comment]
@mdreizin seems to be an issue with installing 1.1.0. A checksum error, possibly created by a bug in the (weird) version of node used to publish the package: `node 0.11.16`.

Can you please unpublish 1.1.0 because it is entirely broken i.e. won't even install, then publish a 1.1.1 using a stable version of node? Sorry to be a pain!

**Comment by mdreizin** [comment]
@timoxley Thanks a lot! I don't know why it was published corrupted. Now I'm going exclude `0.11.16` from the `travis` matrix and republish it again.

**Comment by mdreizin** [comment]
Please update to `1.1.1`.

**Comment by mdreizin** [comment]
@timoxley Please update to `1.1.1`.

**Comment by mdreizin** [comment]
@basketofsoftkittens @timoxley @tmpvar @pheuter can I close it now?

**Comment by timoxley** [comment]
@mdreizin looks like it worked :+1:

**Comment by mdreizin** [comment]
@timoxley you also can update to the latest version, but you need to do some migration.

**Comment by timoxley** [comment]
@mdreizin I migrated to webpack-config@1.1.1. is this not the latest version?

**Comment by mdreizin** [comment]
@timoxley this is the latest.

**Comment by gkats** [comment]
I'm having the same issue that @pheuter describes. 

I am on an old version of `gulp-webpack-build`. The problem is that newer versions of the module (0.12+) depend on latest versions of webpack (1.12+). Updating gulp-webpack-build means I also have to update webpack which opens up a can of worms.

I certainly don't want to complain or anything and I know that I should update at some point (I'm too far behind). My question is, are you still following the issue with npm support, or is updating the only realistic option right now? 

Thanks a lot.

**Comment by mdreizin** [comment]
Hello @gkats, 

I'm sorry for this inconvenience.

Unfortunately there is no way to use the old version `gulp-webpack-build`, because `webpack-config` has been accidentally unpublished.

You have two choices:
* use old [gulp-webpack-build#0.13.1](https://www.npmjs.com/package/gulp-webpack-build)
* migrate to new [webpack-config-stream](https://www.npmjs.com/package/webpack-config-stream)

Anyway I can assist with migration.

**Comment by gkats** [comment]
Thanks for the reply @mdreizin. I guess it's time for an update after all :smile:.

**Comment by IngwiePhoenix** [comment]
NPM fails? Mhm, here too.
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ npm i --save webpack-config
npm http request GET https://registry.npmjs.org/webpack-config
npm http 200 https://registry.npmjs.org/webpack-config
npm http fetch GET https://registry.npmjs.org/webpack-config/-/webpack-config-1.1.1.tgz
npm http fetch 200 https://registry.npmjs.org/webpack-config/-/webpack-config-1.1.1.tgz
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "--save" "webpack-config"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ingwie/Work/BIRD3/npm-debug.log
```

**Comment by mdreizin** [comment]
@IngwiePhoenix It should work. Please try to run:

- `rm -rf node_modules/`
- `npm cache clean`
- `npm install webpack-config --save`

I have just run `npm install webpack-config --save` on `node 5.0.0` using `npm 3.3.6` and it works.
